classifier_settings = {
    "n_estimators": 100,
    "criterion": "gini",
    "max_depth": None,
    "min_samples_split": 30,
    "min_samples_leaf": 10,
    "min_weight_fraction_leaf": 0.0,
    "max_features": "sqrt",
    "min_impurity_decrease": 0.0,
    "bootstrap": True,
    "oob_score": True,
    "n_jobs": None,
    "random_state": None,
    "verbose": 0,
    "warm_start": False,
    "class_weight": "balanced",
    "ccp_alpha": 1.09e-4,
    "max_samples": 0.86,
}